dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
- rm local_settings.py
deploy:
  provider: heroku
  app: applm1
  strategy: git
  api_key:
    secure: uJWYdSTus5uxa1nxm8WNt+tu2AO3ZK/xza39z0+ITlTYKn7Y+SgjBZ9+Sm3YG1tzXTjwJL3itQfkXoy4sPKtcVd6pM2HSu3/0on42QsGvOBxxjMSweWoDfltXs//9Dj28MVXSUvHYeGUNOHNKaEzJDkArdasEl3iB6MuoFiE/QrQCGSk05nXyKaAhgl+EPj/XktlvD4xbUU8aE1NXX0OgwMilVEo2mKQ4NF9T/2z9ZGC6YBpEEjPYG2y7oncXugUuP7x/Y88dRNrZtyszpuZfoKn/tVfHkJ/3ESumpHEGuIsY2lRkK2LeUXCeMEljF5QQKH5I9cEbn6sJEgZlOG4EHiEtUBDr8g453P9GUrN5g6CqyKLf6LDUiV0xpVKGOJ4J+YZJHYuTgIPYwAlSfIwDz04l9KkJYGQjTzzoyRLx5oAton9uorCJXeK5JY5RIa6Qd2d+Y2VaAo4cquLJMV9xETHD5JK5W322FRqKa3GkQ+9dIYNimbkmhmne01aBqsn+By0uH4nr4CnAT671+7xq0c/V1jCdqLB8g8DgZeLqqFPeZHkhZwTUi5AufoapYZsOvIqWw+XCVdPF6V4sY309VXS6JOP87CIf71nIPA0CluBS4ignY5YaTNtItvvPewAVFWueVVwGJedl9GyjMmOSxPHyjV9SGcfnJr8NuBaZ48=
